export const USER_INFO_SET = 'USER_INFO_SET';
export const USER_INFO_SET_LOADING_STATUS = 'USER_INFO_SET_LOADING_STATUS';

export const CATEGORIES_SET = 'CATEGORIES_SET';
export const CATEGORIES_SET_LOADING_STATUS = 'CATEGORIES_SET_LOADING_STATUS';

export const UNIQUE_SET = 'UNIQUE_SET';
export const UNIQUE_SET_LOADING_STATUS = 'UNIQUE_SET_LOADING_STATUS';

export const FEED_SET = 'FEED_SET';
export const FEED_APPEND = 'FEED_APPEND';
export const FEED_SET_LOADING_STATUS = 'FEED_SET_LOADING_STATUS';

export const TOP_SET = 'TOP_SET';
export const TOP_SET_LOADING_STATUS = 'TOP_SET_LOADING_STATUS';

export const FAVES_SET = 'FAVES_SET';
export const FAVES_APPEND = 'FAVES_APPEND';
export const FAVES_SET_LOADING_STATUS = 'FAVES_SET_LOADING_STATUS';

export const MY_LIKES_SET = 'MY_LIKES_SET';
export const MY_LIKES_SET_LOADING_STATUS = 'MY_LIKES_SET_LOADING_STATUS';


export const MY_VIEWS_SET = 'MY_VIEWS_SET';
export const MY_VIEWS_SET_LOADING_STATUS = 'MY_VIEWS_SET_LOADING_STATUS';
